name: Deploy to staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh-keyscan -H 34.207.129.249 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/ssh_key ubuntu@34.207.129.249 '
            echo "Starting deployment..." &&
            cd ~/bms &&
            echo "Pulling latest changes..." &&
            git pull &&
            echo "Installing dependencies..." &&
            pnpm install &&
            echo "Building project..." &&
            pnpm run build &&
            echo "Restarting services..." &&
            pm2 restart all &&
            echo "Deployment completed!"
          '