name: Deploy to staging
on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster

    steps:
      - name: SSH into server
      - run: |
          echo  {{ secrets.SSH_PRIVATE_KEY }} &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@34.207.129.249
          cd bms/ && git pull
          pnpm install
          pnpm run build
          pm2 restart web
          pm2 restart http-server
          pm2 restart ws-server



